### ISSUE TITLE
`pyiron_workflow` syntax

### ISSUE THREAD

**Issue by liamhuber** [pyiron-dev/compare-workflow-graphs#5]
I promised [in the meeting this week](https://github.com/orgs/pyiron/discussions/237#discussioncomment-10115242) to show how to extend the `pyiron_workflow` example to access collections of nodes and edges independently. Nodes are super easy, it's just `wf.children`. Per my disclaimer, the current access to edges is still pretty ugly as it's only intended for internal use right now:

```python
print(wf.children)
# A bidict of child labels and instances
# bidict.bidict[str, Node]

print(wf._child_data_connections)
# A list of nested tuples for all connections:
# ((child1 label, channel name), (child2 label, channel name)
# list[tuple[tuple[str, str], tuple[str, str]]]

print(wf._child_signal_connections)
# The same format as data connections
```

In the process, I noticed the workflow example is a little weird:

```python
wf.x = 1
wf.y = 2
wf.z = add_x_and_y(x=wf.x, y=wf.y)
wf.w = add_x_and_y_and_z(x=wf.x, y=wf.y, z=wf.z)

```

In this case `wf.x` and `wf.y` are just regular attributes of the `wf` object. The example runs fine, but these fields don't appear in renderings of the workflow diagram and these input values can't be passed as arguments at run/call time -- they can only be updated by going back and changing the attribute. To really incorporate this input as part of the workflow these should read:

```python
wf.x = Workflow.create.standard.UserInput(1)
wf.y = Workflow.create.standard.UserInput(2)

```

Finally, a little while ago I introduced something called the `full_label` to the semantic objects. I think this is a great place for getting a much more human-readable representation of the edges:

```python
for child in wf:
    for channel in child.outputs:  # For execution signals: child.signals.output
        for connection in channel.connections:
            print(channel.full_label, "-->", connection.full_label)
>>> /my_workflow/x.user_input --> /my_workflow/w.x
>>> /my_workflow/x.user_input --> /my_workflow/z.x
>>> /my_workflow/y.user_input --> /my_workflow/w.y
>>> /my_workflow/y.user_input --> /my_workflow/z.y
>>> /my_workflow/z.z --> /my_workflow/w.z

```

**Comment by jan-janssen** [comment]
I close this issue, as by now we use the `wf.graph_as_dict` functionality to get the whole graph resolved as dictionary without iterating over the children manually.
